"""Add email and hashed_password to users table

Revision ID: <new_revision_id>
Revises: 54738d0146de
Create Date: 2025-08-16 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, None] = '54738d0146de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True), schema='pos')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], schema='pos')
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True), schema='pos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password', schema='pos')
    op.drop_constraint(op.f('uq_users_email'), 'users', schema='pos')
    op.drop_column('users', 'email', schema='pos')
    # ### end Alembic commands ###
