"""Add timestamps to all tables

Revision ID: 3fa3261d0d62
Revises: 6e74ff0b0345
Create Date: 2025-08-16 23:47:12.615813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa3261d0d62'
down_revision: Union[str, Sequence[str], None] = '6e74ff0b0345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True), schema='pos')
    op.add_column('subscription_products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema='pos')
    op.add_column('customers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True), schema='pos')
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema='pos')
    op.add_column('prices', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True), schema='pos')
    op.add_column('prices', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema='pos')
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema='pos')
    op.alter_column('subscriptions', 'created', new_column_name='created_at', existing_type=sa.DateTime(timezone=True), schema='pos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'created_at', new_column_name='created', existing_type=sa.DateTime(timezone=True), schema='pos')
    op.drop_column('subscriptions', 'updated_at', schema='pos')
    op.drop_column('prices', 'updated_at', schema='pos')
    op.drop_column('prices', 'created_at', schema='pos')
    op.drop_column('customers', 'updated_at', schema='pos')
    op.drop_column('customers', 'created_at', schema='pos')
    op.drop_column('subscription_products', 'updated_at', schema='pos')
    op.drop_column('subscription_products', 'created_at', schema='pos')
    # ### end Alembic commands ###
