-- Asegurarse de que la tabla stock_transfer_items exista
CREATE TABLE IF NOT EXISTS pos.stock_transfer_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stock_transfer_id UUID REFERENCES pos.stock_transfers NOT NULL,
  product_id UUID REFERENCES pos.products_inventory NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(19, 4) NOT NULL,
  total_amount DECIMAL(19, 4) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS para la tabla
ALTER TABLE pos.stock_transfer_items ENABLE ROW LEVEL SECURITY;

-- Enable Row Level Security on all tables
ALTER TABLE pos.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.business_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.business_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.products_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.product_inventory_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.stock_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.stock_adjustment_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.stock_transfers ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.customers_pos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.taxes ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.discounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.table_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.menu_modifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.menu_modifier_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.menu_item_modifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.order_item_modifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.kitchen_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.kitchen_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.analytics_data ENABLE ROW LEVEL SECURITY; 